### ISSUE TITLE
Error response from daemon: unknown or invalid runtime name: nvidia

### ISSUE THREAD

**Issue by alexonpeace** [matatonic/openedai-speech#1]
```
docker compose up
[+] Running 0/0
 - Container openedai-speech-server-1  Creating                                                                                                                                                             0.0s
Error response from daemon: unknown or invalid runtime name: nvidia
```

**Comment by alexonpeace** [comment]
I'm trying to run this on docker desktop

**Comment by alexonpeace** [comment]
It works without the
```
runtime: nvidia
deploy:
  resources:
    reservations:
      devices:
        - driver: nvidia
          #device_ids: ['0', '1'] # Select a gpu, or
          count: all
          capabilities: [gpu]
```
but how do I make it run with GPU

**Comment by matatonic** [comment]
I think all you need to do is setup wsl2 and enable wsl2 in docker desktop and run it from there. As I understand it, in windows the 'runtime' and 'deploy' sections are not required after you do this. Here is a video that should detail the steps: https://www.youtube.com/watch?v=PB7zM3JrgkI

**Comment by jmtatsch** [comment]
the `runtime: nvidia` throws the same error for me as well and I have a bunch of nvidia accelerated containers running just fine.

as per https://stackoverflow.com/questions/52865988/nvidia-docker-unknown-runtime-specified-nvidia

runtime: nvidia is just for nvidia-docker2 which is outdated.

**Comment by matatonic** [comment]
@alexonpeace - can you confirm this? Looks like the deploy section is still required to enable gpus even with an nvidia compatible runtime

**Comment by alexonpeace** [comment]
it works  👍
