### ISSUE TITLE
Fine Tuned xttsv2

### ISSUE THREAD

**Issue by ther3zz** [matatonic/openedai-speech#12]
I see that this supports voice cloning but I haven't seen anywhere in the docs that this can be used with a fine tuned xtts v2 model.

Is that currently possible?

**Comment by matatonic** [comment]
I've thought to add it but I haven't looked into it yet - do you have some references for me so I can quick start? How is a finetuned xtts model normally used?

**Comment by ther3zz** [comment]
> I've thought to add it but I haven't looked into it yet - do you have some references for me so I can quick start? How is a finetuned xtts model normally used?

You'll have to bear with me, I have no idea what I'm doing.

I'm currently running it like:
tts-server --model_path /models/model.pth --config_path /models/config.json --use_cuda true --speakers_file_path /models/sample.wav

there's some sample inference code here: https://docs.coqui.ai/en/latest/models/xtts.html#advanced-training

I actually had to modify [xtts.py](https://github.com/ther3zz/TTS/blob/dev/TTS/tts/models/xtts.py) , [server.py](https://github.com/ther3zz/TTS/blob/dev/TTS/server/server.py)  and the [config module](https://github.com/ther3zz/TTS/blob/dev/TTS/config/__init__.py) to even get xtts-server to use the fine tuned model.

The changes are also relevant to the marytts api since my use case is home assistant

**Comment by matatonic** [comment]
Do you still use the reference_wav with a custom model?

**Comment by ther3zz** [comment]
> Do you still use the reference_wav with a custom model?

LOL, you know what, probably not needed with a fine tuned model and I didnt even think about it until you mentioned it now.
I'm going to test without passing the reference wav to see what happens...

**Comment by matatonic** [comment]
btw, this looks like a simpler change (model_path, config_path) instead of (model_name)

**Comment by matatonic** [comment]
I don't have a model to test with...

**Comment by ther3zz** [comment]
> > Do you still use the reference_wav with a custom model?
> 
> LOL, you know what, probably not needed with a fine tuned model and I didnt even think about it until you mentioned it now. I'm going to test without passing the reference wav to see what happens...

So I got an error when I didnt pass either speaker_idx or speaker_wav so it looks like one of those are required.



> I don't have a model to test with...

I can share one if needed

**Comment by matatonic** [comment]
speaker_idx=0 may work - and yes if I can, that would be helpful.

**Comment by ther3zz** [comment]
How should I contact you without making the link available to everyone?

**Comment by matatonic** [comment]
I'm on discord as matatonic in TheBloke AI, Text Generation WebUI and open-webui discords if that works, you can DM me there.

**Comment by matatonic** [comment]
Planned for next release.
