### ISSUE TITLE
AMD GPU

### ISSUE THREAD

**Issue by G4Zz0L1** [matatonic/openedai-speech#13]
As the title suggests, is there any chance that this project could work with PyTorch for AMD GPUs?

**Comment by matatonic** [comment]
I don't have any way to test with AMD, but I did find this forked repo yesterday and it seems promising, maybe you can let me know if it works: https://github.com/jamfor352/openedai-speech
They include the rocm torch and a few other details (devices). No Idea if it works!

**Comment by Airradda** [comment]
Based on the spike in GPU usage and faster response time, it appears to be properly utilizing my AMD GPU. :+1:

**Comment by matatonic** [comment]
Thanks for the report! I wasn't able to test it myself.
