### ISSUE TITLE
Silent failure to generate speech

### ISSUE THREAD

**Issue by bublint** [matatonic/openedai-speech#32]
I am experiencing a silent failure to generate speech. The resulting .mp3 file is always empty, containing 1 second of silence. I have tried both the Docker installation and the non-Docker installation on my baremetal Ubuntu server and on Ubuntu running in WSL2 on my Windows 10 machine.

**Steps to Reproduce:**
1. Clone the repository.
2. Follow the Docker installation instructions.
3. `docker compose -f docker-compose.min.yml up`
4. Run the following command: 
```curl http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{
  "model": "tts-1",
  "input": "The quick brown fox jumped over the lazy dog.",
  "voice": "alloy",
  "response_format": "mp3",
  "speed": 1.0
}' > speech.mp3
```

**Expected Result:**
An .mp3 file with the generated speech.

**Actual Result:**
An .mp3 file containing 1 second of silence.

**Additional Information:**
When changing the TTS model to tts-1-hd, the resulting file has 2 seconds of silence instead of 1.

**Logs:**
The debug logs appear normal and show a successful response:
```[+] Running 1/0
 ✔ Container openedai-speech-server-1  Created                                                                     0.0s
Attaching to server-1
server-1  | INFO:     Started server process [13]
server-1  | INFO:     Waiting for application startup.
server-1  | INFO:     Application startup complete.
server-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
server-1  | 2024-07-12 02:33:50.090 | DEBUG    | openedai:log_requests:120 - Request path: /v1/audio/speech
server-1  | 2024-07-12 02:33:50.091 | DEBUG    | openedai:log_requests:121 - Request method: POST
server-1  | 2024-07-12 02:33:50.091 | DEBUG    | openedai:log_requests:122 - Request headers: Headers({'host': 'localhost:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '158'})
server-1  | 2024-07-12 02:33:50.091 | DEBUG    | openedai:log_requests:123 - Request query params:
server-1  | 2024-07-12 02:33:50.091 | DEBUG    | openedai:log_requests:124 - Request body: b'{\n    "model": "tts-1",\n    "input": "The quick brown fox jumped over the lazy dog.",\n    "voice": "alloy",\n    "response_format": "mp3",\n    "speed": 1.0\n  }'
server-1  | 2024-07-12 02:33:50.099 | DEBUG    | openedai:log_requests:128 - Response status code: 200
server-1  | 2024-07-12 02:33:50.099 | DEBUG    | openedai:log_requests:129 - Response headers: MutableHeaders({'content-type': 'audio/mpeg'})
server-1  | INFO:     172.19.0.1:49232 - "POST /v1/audio/speech HTTP/1.1" 200 OK
```

**Configuration Files:**
docker-compose.yml:
```services:
  server:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/matatonic/openedai-speech
    env_file: speech.env
    ports:
      - "8000:8000"
    volumes:
      - ./voices:/app/voices
      - ./config:/app/config
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

speech.env:
```TTS_HOME=voices
HF_HOME=voices
PRELOAD_MODEL=xtts
#PRELOAD_MODEL=xtts_v2.0.2
EXTRA_ARGS=--log-level DEBUG
#USE_ROCM=1
```

Please let me know if there's any additional information I should include. Thank you for looking into this issue!

**Comment by matatonic** [comment]
Can you include a listing of your voices directory? I'm looking for the onnx and onnx.json files, and their sizes. do all voices produce the same 1 second mp3? please attach the mp3 file also.

I admit, so far I have no idea! piper normally works perfectly, it's so simple and the only other part of this would be ffmpeg - but if you're using the prebuilt docker images... they've all been tested and only need a cpu, not GPU.

**Comment by bublint** [comment]
voices directory:
``` alloy-alt.wav                                 en_US-libritts_r-medium.onnx       put_your_voices_here.txt
alloy.wav                                     en_US-libritts_r-medium.onnx.json  shimmer.wav
echo.wav                                      fable.wav                          tts
en_GB-northern_english_male-medium.onnx       nova.wav                           voices.json
en_GB-northern_english_male-medium.onnx.json  onyx.wav
```
Here's the speech.mp3: https://file.io/IsE3JARLHlAm
It does seem like every voice is producing the same result. I'm going to try some more fresh installs to see if I can narrow things down any further.

**Comment by matatonic** [comment]
Well, I hate to be the bearer of good news (bad news?) but the problem may be that you don't have a functioning audio setup. That mp3 plays fine for me. "The quick brown fox jumped over the lazy dog." I think you need to test with some other mp3 files, but it looks like openedai-voice is working fine.

**Comment by bublint** [comment]
That was not what I expected at all! Turns out I was using the generic windows audio drivers, which for some reason resulted in my system not being able to output mono audio in a 5.1 configuration. Ended up being a little difficult to track down because almost everything apparently defaults to stereo. Resolved by installing the correct drivers.
