### ISSUE TITLE
[Feature Request] Add a global option to prepend and append silence

### ISSUE THREAD

**Issue by raldone01** [matatonic/openedai-speech#33]
Thanks for you work. This project is really great.

However with most clients I use the beginning and ending are sometimes cut off. This could be mitigated by adding a configurable `SILENCE_START` and `SILENCE_END` environment variables (in ms) to the docker container.

**Comment by matatonic** [comment]
I'm interested in understanding how the audio is getting cut off in the first place - is this a generation issue or a client issue? Something else?

**Comment by raldone01** [comment]
I tried it a lot more and found the issue.
My amplifier enters a sleep mode and then cuts off audio in the beginning.
When I listen to music in the background it does not get cut off.

Thanks for your project. It's working great.

Just a small note:

Consider documenting: `- EXTRA_ARGS=--unload-timer=150` otherwise vram is never freed.
Also the `unload-timer` does not seem to completely release the gpu device which prevents sleep modes on my `P40` (50W usage instead of 10W).

And one short question:

Is there a way to enumerate all available voices via the api?

**Comment by matatonic** [comment]
Re: not completely release the device, thanks for the confirmation, I was not able to get it to drop the last remaining bytes (some hundreds of MB), and I don't know how either (!), I tried a number of documented ways but there's always left over. I didn't realize it would also have power impact, thanks for pointing that out... I'll keep looking.

Re: enumerating voices - no, but I wish there was. openai doesn't have anything like that for voices, just models (and only the most basic support for listing models).

**Comment by raldone01** [comment]
I think some projects create a subprocess for the gpu stuff which is stopped when it should be released but that may be inconvenient.
A useful tool to debug power draw and memory usage is `nvtop`.

I have two P40s, one is always running anyways so I just put speech there too.
So it doesn't impact me too much but may impact others.

**Comment by matatonic** [comment]
Subprocess for gpu - yeah, that's the only idea I had so far also. Thanks!
