### ISSUE TITLE
The TTS OpenAI configuration has not taken effect.

### ISSUE THREAD

**Issue by johnyu0** [matatonic/openedai-speech#36]
I have configed the tts use OPENAI
http://host.docker.internal:8000/v1
![image](https://github.com/user-attachments/assets/4450db68-7c22-4a79-97de-fcf4f1f36b69)
I think the open-webui should call the openai api http://host.docker.internal:8000/v1.
But the Open-webui still call the index.ts:105 
        res = await fetch(`${AUDIO_API_BASE_URL}/speech`
the console log is：
       POST http://192.168.1.240:3000/audio/api/v1/speech 400 (Bad Request)

**Comment by matatonic** [comment]
Hi, I've been out of the country with limited internet access - has this been resolved? Your open-webui setup looks ok so far, but what about the openedai-speech config and setup?

**Comment by johnyu0** [comment]
![image](https://github.com/user-attachments/assets/0da40118-0c20-488d-9eda-672ace8943b7)
I have test the opend-speech on the open-webui host. It seems ok

**Comment by johnyu0** [comment]
> Hi, I've been out of the country with limited internet access - has this been resolved? Your open-webui setup looks ok so far, but what about the openedai-speech config and setup?

It looks like the open-webui didn't use the openai api configuration, according the console log. Because the open-webui using http://XXXXXx:3000/audio/api/v1/speech.

**Comment by matatonic** [comment]
http://xxxxxx:3000/audio/api/v1/speech is correct in the open-webui logs, you need to look at the openedai-speech logs.

>> I have test the opend-speech on the open-webui host. It seems ok

203 bytes seems too small, can look at the contents of the file? Or just run the curl command without " > speech.mp3"

**Comment by johnyu0** [comment]
![image](https://github.com/user-attachments/assets/3bf0ea1d-102b-4145-9974-bba7c7eb7ba2)
I have reintalled the openedai-speech by docker-compose follow the open-webui documents. But the 500 (Internal Server Error) is still exists in the open-webui console log.

**Comment by johnyu0** [comment]
> http://xxxxxx:3000/audio/api/v1/speech is correct in the open-webui logs, you need to look at the openedai-speech logs.
> 
> > > I have test the opend-speech on the open-webui host. It seems ok
> 
> 203 bytes seems too small, can look at the contents of the file? Or just run the curl command without " > speech.mp3"

Thank you very much! It's ok now. 
However it runs on the cuda, but the speed of tts is very slow.

**Comment by matatonic** [comment]
Great! can you define slow for me? on a 4090, you can expect about 2-3x real time generation.

**Comment by matatonic** [comment]
Closing this now, let me know if there is anything more.
