### ISSUE TITLE
CUDA acceleration broken

### ISSUE THREAD

**Issue by jmtatsch** [matatonic/openedai-speech#4]
FROM python:3.11-slim in the non-minimal docker file is not enough to get Cuda support.
Consider this: [2.3.0-cuda12.1-cudnn8-runtime](https://hub.docker.com/layers/pytorch/pytorch/2.3.0-cuda12.1-cudnn8-runtime/images/sha256-0279f7aa29974bf64e61d0ff6e979b41a249b3662a46e30778dbf80b8c99c361?context=explore) as TTS requires torch>2.1
Yes that will make image huge (+3.5GB) but I think there is no slim cuda images.

**Comment by matatonic** [comment]
The nvidia/cuda packages are install via pip, the cuda image isn't required but enabling specific gpus is required. For example:

```
$ docker run --gpus=all --rm ghcr.io/matatonic/openedai-speech  python -c "import torch; print(torch.cuda.is_available())"
True
$ docker run --rm ghcr.io/matatonic/openedai-speech  python -c "import torch; print(torch.cuda.is_available())"
False
```
