### ISSUE TITLE
Ignore "*" symbol in speaking

### ISSUE THREAD

**Issue by PPTG** [matatonic/openedai-speech#41]
How I can setup ignoring "*" symbol in speeking ?

**Comment by matatonic** [comment]
In the config/pre_process_map.yaml file, you can add this at the bottom:

```yaml
- - '\*'
  - ''
```

This will completely remove all '*'  characters, replace with ' ' if you want to replace as a space instead.

I will add this as a default in future releases.

**Comment by matatonic** [comment]
This is what I plan to add:
```
- - '[\*=+-]+'
  - ' '
```

**Comment by PPTG** [comment]
Thanks ! :)

**Comment by matatonic** [comment]
Just for the record, and anyone else reading this, this comment and example was added to the `pre_process_map.default.yaml` file

```
# xtts has a lot of trouble with these, but piper is fine.
#- - '[\*=+-]+'
#  - ' '
```
