### ISSUE TITLE
no amd64 docker image for 0.18.1 and latest tags

### ISSUE THREAD

**Issue by AnonTester** [matatonic/openedai-speech#43]
There's no AMD64 docker image available for 0.18.1 and latest. Not showing in the releases either. Last AMD64 docker image is still 0.17.2

See docker pull output:
```
docker pull ghcr.io/matatonic/openedai-speech:0.18.1
0.18.1: Pulling from matatonic/openedai-speech
no matching manifest for linux/amd64 in the manifest list entries

docker pull ghcr.io/matatonic/openedai-speech:latest
latest: Pulling from matatonic/openedai-speech
no matching manifest for linux/amd64 in the manifest list entries

```

**Comment by matatonic** [comment]
damn, thanks for the report, I started having all kind of trouble building images yesterday... out of disk space, etc. Anyways...

**Comment by matatonic** [comment]
Ok, 0.18.2 just finished building and should resolve the issue. If you pull :latest now it should work again also, sorry for any inconvenience! Github seems to have changed the worker images recently and they leave almost no free space by default.
