### ISSUE TITLE
Langdetect is 100 times slower than fasttext-langdetect

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [matatonic/openedai-speech#45]
Tested using ipython on python 3.11

```
In [7]: %timeit ftlangdetect.detect("bonjour, je viens de me reveiller")
18.4 μs ± 4.8 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [8]: %timeit langdetect.detect("bonjour, je viens de me reveiller")
21.3 ms ± 9.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

One gotcha is that ftlangdetect crashes if there is a newline so what I did on some other project is simply replace nexlines by a space for example.

https://pypi.org/project/fasttext-langdetect/

**Comment by matatonic** [comment]
I tested added fasttext-langdetect to the -min image it it ends up requiring to build it, so needs compilers, etc. This really complicates the dockerfile and ends up needing a separate builder image to maintain the small -min image. For now, I'm not going to include this due to the added complexity, lower quality and additional work required.

It's just not worth the 20ms, I think more people would notice the -5% reduction in correct detection than the 20ms.

Thanks for the suggestion, it would 100% be better when used in tiny systems like a raspberry pi so I do think there is a case for it somewhere.

**Comment by matatonic** [comment]
Well, maybe exaggerated the Docker impact, but it's like 36% larger in the image (1.17GB vs 863MB). I don't like the loss of quality and I think making it optional is even more complex. I could detect and use it if installed, but I don't want to bake it into the docker image.

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot, just a quick thought: i didn't check how the speed gain scales as the text size grows. 20ms is not much but if we're not cropping the text at a fix length maybe there's a real gap for longer text?

**Comment by matatonic** [comment]
That's possible. And I'm still actually looking at it, the fact that langcheck is from 2013 and fasttext was updated as recently as 6 months ago is significant. 

low_memory=True - is it worth it?

```python
try:
    from fasttext-langdetect import detect as fasttext_detect

    def detect(text):
        # convert fasttext language codes
        lang_map = {
            'zh': 'zh-cn'
        }
        lang = fasttext_detect(text, low_memory=True)['lang']
        return lang_map.get(lang, lang)

except:
    from langdetect import detect
```

**Comment by matatonic** [comment]
On disk, the full model is 127MB, the low_memory one is ~1MB. Have you compared them? langdetect is pretty microscopic by comparison.

In memory, fasttext says the model takes over 200MB ram in low memory mode.

**Comment by matatonic** [comment]
This project seems updated: https://github.com/LlmKira/fast-langdetect
but the code for just using it direct from fasttext seems even simpler and I can bake the small model into the docker image.

**Comment by matatonic** [comment]
https://modelpredict.com/language-identification-survey
I think that settles it, I'm going to switch it to fasttext with the low memory model, I was under the impression that langdetext was better (nope!)

**Comment by thiswillbeyourgithub** [comment]
Nothing to add really, thanks for all the work!

**Comment by thiswillbeyourgithub** [comment]
Thanks a bunch I've been using langdetect for a while and never knew so I'll update my apps :)
