### ISSUE TITLE
Cant curl a fine-tuned xtts-v2 model

### ISSUE THREAD

**Issue by marianbasti** [matatonic/openedai-speech#46]
Hi there!
Been struggling for a couple of days with this.

I set up the model in `voice_to_speaker.yml` as it's specified in the readme:
```yaml
tts-1-hd:
  argentinian:
    model: argentinian
    model_path: voices/argentinian
    speaker: voices/argentinian/sample.wav
```
and copy the files in the specified folder.

I then deploy the API on Ubuntu with docker compose.

When I try it out with curl:
```sh
curl http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{
    "model": "argentinian",
    "input": "The quick brown fox jumped over the lazy dog.",
    "response_format": "mp3",
    "speed": 1.0
  }' > speech.mp3
```
Which yields the error `BadRequestError(message='No such model, must be tts-1 or tts-1-hd.', code=400, param=model)`

If I try with that model name, like so:
```sh
curl http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{
    "model": "tts-1-hd",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "argentinian",
    "response_format": "mp3",
    "speed": 1.0
  }' > speech.mp3
```

I get `BadRequestError(message="Error loading voice: argentinian, KeyError: 'argentinian'", code=400, param=voice)`

I keep banging my head with this. What am I missing?

**Comment by matatonic** [comment]
Your config looks correct. Have you tried enabling debugging?

This is the correct usage:

```
curl http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{
    "model": "tts-1-hd",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "argentinian",
    "response_format": "mp3",
    "speed": 1.0
  }' > speech.mp3
```

Are you using the `-min` image? If so you need to switch to using the default image, the `-min` image doesn't support xtts.

Try enabling debugging in your speech.env:
```
EXTRA_ARGS=--log-level DEBUG
```

Can you share the contents of the voices/argentinian folder?

Another

**Comment by marianbasti** [comment]
I finally opted to build my own API to fit my needs.

To answer your question, I used the default image.

The voices/argentinian directory has `config.json` `vocab.json` and `model.pth`, besides some irrelevant files.

I no longer have an environment set up to test a more verbose run :/

**Comment by matatonic** [comment]
I guess perhaps your config file was not used at all, perhaps in the wrong docker volume? Without more information, I think this is a closed case.

**Comment by marianbasti** [comment]
In
