### ISSUE TITLE
CPU support for Coqui.ai

### ISSUE THREAD

**Issue by nkeilar** [matatonic/openedai-speech#47]
I noted that CPU only support seems possible:

https://docs.coqui.ai/en/latest/docker_images.html

Is there any technical reason we could not utilize this, even if slower, on CPU?

**Comment by matatonic** [comment]
Not at all, you certainly can. Use `--xtts_device cpu` if you want to force loading xtts onto CPU. If you don't have a GPU, this should happen automatically.

**Comment by matatonic** [comment]
If using the docker, just set this in your speech.env:

```
EXTRA_ARGS=--xtts_device cpu
```
