### ISSUE TITLE
docker compose seems to fail

### ISSUE THREAD

**Issue by jojasadventure** [matatonic/openedai-speech#52]
Hi, I ran into an issue running on Docker Compose where the endpoint runs but returns 500, and logs several times "pipe:: Invalid data found when processing input"
I believe it may be the script to download the HD voices, the first one runs fine.
To troubleshoot I attempted to uncomment one of the preload models in the .env file, as I thought the empty variable was causing the error, but then I get a different error which I've also pasted below. 
Apologies, I may have trouble following the set up instructions and just be doing something dumb. 
Any pointers would be much appreciated. (Ubuntu 24, RTX 3090) 

.env file
`TTS_HOME=voices
HF_HOME=voices
PRELOAD_MODEL=xtts
#PRELOAD_MODEL=xtts_v2.0.2
#PRELOAD_MODEL=parler-tts/parler_tts_mini_v0.1`

compose file

`version: '3'

services:
  server:
    image: ghcr.io/matatonic/openedai-speech
    container_name: openedai-speech
    env_file: .env
    ports:
      - "8008:8000"
    volumes:
      - tts-voices:/app/voices
      - tts-config:/app/config
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  tts-voices:
  tts-config:
`

error
`
docker compose logs -f
WARN[0000] /home/j/openedai-speech-service/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
openedai-speech  | First startup may download 2GB of speech models. Please wait.
openedai-speech  | First startup may download 2GB of speech models. Please wait.
openedai-speech  | pipe:: Invalid data found when processing input
openedai-speech  | pipe:: Invalid data found when processing input
openedai-speech  | pipe:: Invalid data found when processing input
openedai-speech  | pipe:: Invalid data found when processing input
openedai-speech  | pipe:: Invalid data found when processing input
openedai-speech  | pipe:: Invalid data found when processing input
openedai-speech  | 2024-08-26 17:23:35.825 | INFO     | __main__:__init__:59 - Loading model xtts to cuda
openedai-speech  | Traceback (most recent call last):
openedai-speech  |   File "/app/speech.py", line 440, in <module>
openedai-speech  |     xtts = xtts_wrapper(args.preload, device=args.xtts_device, unload_timer=args.unload_timer)
openedai-speech  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openedai-speech  |   File "/app/speech.py", line 66, in __init__
openedai-speech  |     config.load_json(config_path)
openedai-speech  |   File "/usr/local/lib/python3.11/site-packages/coqpit/coqpit.py", line 726, in load_json
openedai-speech  |     with open(file_name, "r", encoding="utf8") as f:
openedai-speech  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openedai-speech  | FileNotFoundError: [Errno 2] No such file or directory: '/app/voices/tts/tts_models--multilingual--multi-dataset--xtts/config.json'
`

**Comment by matatonic** [comment]
Hi, not sure how I missed this yesterday - the format came through very poorly, can you wrap it in triple back ticks? "```"

**Comment by matatonic** [comment]
Also, you might try the :dev version of the image currently in development.

**Comment by matatonic** [comment]
Perhaps the model was corrupted? You could try: 
```shell
sudo rm -r voices/tts/
```

And restart it.

**Comment by jojasadventure** [comment]
Hi, apologies for the poor formatting!  also uhhh I was shadowbanned by github (for having a simplelogin alias mail address on my domain) which I had to contact them to find out and I just fixed it. Probably that's why my issue suddenly popped up but with y'day's date.

Compose:
```
version: '3'

services:
  server:
    image: ghcr.io/matatonic/openedai-speech
    container_name: openedai-speech
    env_file: .env
    ports:
      - "8008:8000"
    volumes:
      - tts-voices:/app/voices
      - tts-config:/app/config
    # labels:
    #   - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  tts-voices:
  tts-config:

```

.env  (tried with all preloads commented out, and different preloads, example here, none worked): 
 
```
TTS_HOME=voices
HF_HOME=voices
#PRELOAD_MODEL=xtts
#PRELOAD_MODEL=xtts_v2.0.2
PRELOAD_MODEL=parler-tts/parler_tts_mini_v0.1

```

Then it occurred to me to remove the config and voice docker volumes and give it a clean slate
```
docker volume rm openedai-speech-service_tts-config
docker volume rm openedai-speech-service_tts-voices
```

I seem to be, further. The error has changed...

```
openedai-speech  | First startup may download 2GB of speech models. Please wait.
openedai-speech  | INFO:piper.download:Downloaded voices/en_GB-northern_english_male-medium.onnx (https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx)
openedai-speech  | INFO:piper.download:Downloaded voices/en_GB-northern_english_male-medium.onnx.json (https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx.json)
openedai-speech  | INFO:piper.download:Downloaded voices/en_US-libritts_r-medium.onnx.json (https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx.json)
openedai-speech  | INFO:piper.download:Downloaded voices/en_US-libritts_r-medium.onnx (https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx)
openedai-speech  | Traceback (most recent call last):
openedai-speech  |   File "<string>", line 1, in <module>
openedai-speech  |   File "/usr/local/lib/python3.11/site-packages/TTS/utils/manage.py", line 375, in download_model
openedai-speech  |     model_item, model_full_name, model, md5sum = self._set_model_item(model_name)
openedai-speech  |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openedai-speech  |   File "/usr/local/lib/python3.11/site-packages/TTS/utils/manage.py", line 290, in _set_model_item
openedai-speech  |     model_type, lang, dataset, model = model_name.split("/")
openedai-speech  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openedai-speech  | ValueError: not enough values to unpack (expected 4, got 2)
openedai-speech  | pipe:: Invalid data found when processing input

```

Pulling the dev version right now to try. Thanks for your reply!

**Comment by jojasadventure** [comment]
not having much more luck with the :dev version I'm afraid, though I wiped volumes again and set all preloads to commented-out in the .env file.  (The machine is on a VPN, I know more and more sites are blocking... but then it's usually blocked from the get-go and not in the middle. )
```
[+] Running 4/4
 ✔ Network openedai-speech-service_default      Created                                                                                  0.1s 
 ✔ Volume "openedai-speech-service_tts-voices"  Created                                                                                  0.0s 
 ✔ Volume "openedai-speech-service_tts-config"  Created                                                                                  0.0s 
 ✔ Container openedai-speech                    Created                                                                                  0.0s 
Attaching to openedai-speech
openedai-speech  | First startup may download 2GB of speech models. Please wait.
openedai-speech  | INFO:piper.download:Downloaded voices/en_GB-northern_english_male-medium.onnx (https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx)
openedai-speech  | INFO:piper.download:Downloaded voices/en_GB-northern_english_male-medium.onnx.json (https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx.json)
openedai-speech  | INFO:piper.download:Downloaded voices/en_US-libritts_r-medium.onnx.json (https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx.json)
openedai-speech  | INFO:piper.download:Downloaded voices/en_US-libritts_r-medium.onnx (https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx)
openedai-speech  | pipe:: Invalid data found when processing input

```

**Comment by matatonic** [comment]
So I see you're using the open-webui documentation for installation, that's a bit different than the official install docs. If this is a linux system, I would recommend you use the official install docs which do not use special docker volumes for voices and config folders, but use the local folders config/ and voices/.

Yeah, it looks strange, maybe blocking connections. Try running the download_samples.sh scripts manually, you will need curl and ffmpeg installed.

```shell
mkdir voices
bash download_samples.sh
```

**Comment by jojasadventure** [comment]
It was VPN. Mounted the folders instead of using volumes as you suggested, and ran download script on a clearnet host to get the files without issue. Now solved. Thanks for your patience.

**Comment by matatonic** [comment]
Glad to hear! You should be able to sync anything from the voices/ folder including any piper models or xtts models.
