### ISSUE TITLE
Add Small Gaps Between Audio Chunks to Avoid Rushed Speech

### ISSUE THREAD

**Issue by bi1101** [matatonic/openedai-speech#53]
Hi,

I noticed that the repository uses a really smart approach to account for text length by segmenting the text into smaller chunks and generating audio for each segment separately.

But there's a small issue. The part where the stitching happens is very noticeable. When the audio chunks are stitched together, there are no gaps between them, which makes the resulting speech sound a bit rushed and unnatural.

Can you add this in future versions? Making it configurable via .env would also be nice.

**Comment by matatonic** [comment]
Are you experiencing this with piper or xtts models? both?

**Comment by bi1101** [comment]
I'm experiencing this with xtts, (the piper is rushed by default in my experience, so this is not an issue). With every 2 sentence or so, the audio is kinda rushed to the next sentence without a pause
This is the audio file [response.webm](https://github.com/user-attachments/assets/2d793c6d-f489-41a2-a2ea-3fa4255f6f11)

And the curl
```
{
    "model": "tts-1-hd",
    "input": "Once upon a time in a small village nestled between rolling hills, there lived a young girl named Lila. She was known for her curiosity and love for the stars. Every night, she would climb up the hill behind her house to gaze at the twinkling lights in the sky. Her favorite star was the brightest one, which she named Lumina. One evening, as she was lying on the grass, Lila noticed Lumina flickering strangely. Concerned, she whispered, 'What's wrong, Lumina?' To her amazement, the star responded with a soft glow and a gentle voice, 'I am losing my light, Lila. I need your help.' Determined to save her beloved star, Lila asked, 'What can I do?' Lumina explained that a dark shadow from a distant galaxy was slowly dimming her light. To restore it, Lila would need to gather the light of the purest hearts in her village and send it to Lumina. The next day, Lila set out on a quest. She visited her neighbors, friends, and even the animals in the village, asking for their purest wishes and hopes. She collected them in a small glass jar that sparkled with a soft, golden light. With the jar full, Lila returned to the hill at sunset. Holding the jar high, she whispered a wish for Lumina to shine brightly again. The jar burst open, releasing a beam of golden light that shot up into the sky, enveloping Lumina. The star began to glow with renewed brilliance, brighter than ever before. Lumina twinkled joyfully and thanked Lila for her kindness and bravery. From that night on, Lumina became a guiding star for travelers and a symbol of hope for the village. Lila continued to visit Lumina every night, knowing that the light of a pure heart could brighten even the darkest of skies.",
    "voice": "alloy",
    "response_format": "mp3",
    "speed": "1"
}
```

**Comment by matatonic** [comment]
Pretty subtle, but yeah, I hear it. Have you considered using speed: 0.9?

There is not built in option to add silence in xtts, so the change is fiddling with the wav output in the stream. This will probably not happen by me unless it gets more support, but I'm open to a PR for it.

**Comment by bi1101** [comment]
#55 This should mitigate the issue

**Comment by matatonic** [comment]
Funny, just yesterday I figured this out also (silence was 0s,).
