### ISSUE TITLE
Please help, open webui deployment openedai-speech problem

### ISSUE THREAD

**Issue by zhai-hello** [matatonic/openedai-speech#66]
Deployed according to the tutorial
https://docs.openwebui.com/tutorials/integrations/openedai-speech-integration
1. docker desktop deployment
Encountered problems as shown in the picture
In addition, where can I download the 2G model? The automatic download seems to have been unsuccessful. Where can I download the 2G model and which folder should I put it in?
![01](https://github.com/user-attachments/assets/2342dd2e-bc18-41a0-95ab-205ac785cb2d)
![02](https://github.com/user-attachments/assets/03acd6cf-4eeb-425d-8345-b7acb570ba49)
![03](https://github.com/user-attachments/assets/c4c3f838-8079-48f8-b5f7-dd197db74907)
![04](https://github.com/user-attachments/assets/478d742c-6032-4482-a279-4a20fc247de0)

**Comment by matatonic** [comment]
Are you trying to download from China? If so, perhaps this issue will help you: https://github.com/matatonic/openedai-speech/issues/64

**Comment by zhai-hello** [comment]
> Are you trying to download from China? If so, perhaps this issue will help you: #64

Thank you, I looked at it in detail, but still haven't solved it. Because I am a beginner and only know how to deploy according to the tutorial

**Comment by matatonic** [comment]
Sorry for the delay, I don't have a workaround for this problem yet.

**Comment by zhai-hello** [comment]
> Sorry for the delay, I don't have a workaround for this problem yet.

Thank you very much for your reply. I have solved this problem. The problem lies in the URL. Because my open webui is deployed by docker, the address filled in in the tutorial should not be http://host.docker.internal: 8000/v1, but should be the URL given in the docker container, such as http://172.17.0.1:8000/v1, so it can be used. Thanks again for your project。
