### ISSUE TITLE
TTS

### ISSUE THREAD

**Issue by seth225** [matatonic/openedai-speech#68]
So I just need a little help here.   Ive got Open Webui running on a docker container, and same for Openedai-speech.   However the only tts I am getting in Open Webui is Alloy, and there are multiple voices in the voices folder.   What am I missing?   Please keep it simple Im not much of a tech or programmer.   Thanks

**Comment by matatonic** [comment]
In the settings of open-webui, there is an audio section, you can change the selected voice there.

![image](https://github.com/user-attachments/assets/92146f1b-3f8f-4490-86b5-b7d77fcc82ff)

You can change the default voice for all users, as well as select the model to use (hd or not) in the Admin Panel settings:

![image](https://github.com/user-attachments/assets/7e62cea3-b812-4218-bd75-9bf88621aa4d)

**Comment by matatonic** [comment]
You just need to type the name of the voice you want to use, there is no way to list the available voices in open-webui.

**Comment by seth225** [comment]
OMG so simple.   Problem solved!! Thanks

    On Tuesday, October 1, 2024 at 07:39:52 AM EDT, matatonic ***@***.***> wrote:  
 
 


You just need to type the name of the voice you want to use, there is no way to list the available voices in open-webui.
