### ISSUE TITLE
How to use openedai-speech with coqui_tts as an text-generation-webui extension within Windows?

### ISSUE THREAD

**Issue by guispfilho** [matatonic/openedai-speech#7]
Hi, I was wondering if it's possible to use model 'tts-1-hd' with coqui_tts as an text-generation-webui (Oobabooga) extension within Windows? And if so, how can I get it, other than the .sh file?

**Comment by matatonic** [comment]
It is possible, yes, I'll see about putting together a guide for windows.

**Comment by matatonic** [comment]
Hi, I think I misunderstood you. coqui_tts is a standard extension to text-generation-webui already - did you mean something else?
