### ISSUE TITLE
Sample test code provided didn't work for me with the Docker Container, but Below code Did! It works

### ISSUE THREAD

**Issue by MovLab2** [matatonic/openedai-speech#70]
import requests

# Define the API endpoint
url = "http://localhost:8000/v1/audio/speech"

# Define the JSON payload
payload = {
    "model": "tts-1",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "alloy",
    "response_format": "mp3",
    "speed": .6
}

# Send the POST request
response = requests.post(url, json=payload)

# Check if the request was successful
if response.status_code == 200:
    # Save the response content (audio file) to speech.mp3
    with open("speech.mp3", "wb") as f:
        f.write(response.content)
    print("MP3 file saved successfully as speech.mp3")
else:
    print(f"Error: {response.status_code}")
    print(response.text)

**Comment by matatonic** [comment]
Which sample code? openai reference code or the 'say.py' sample app? Can you share the failure and what didn't work?

**Comment by MovLab2** [comment]
I Just couldn't get it to work. I'm using conda Env full version.
____________________________________________________________________________________________
curl http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{
    "model": "tts-1",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "alloy",
    "response_format": "mp3",
    "speed": 1.0
  }' > speech.mp3

**Comment by matatonic** [comment]
I use it with open-webui yes, what is not working?

**Comment by matatonic** [comment]
Please explain how you installed and set it up to run, as well as how you're trying to use it.

**Comment by MovLab2** [comment]
I used the docker Container from the yaml file you provided.. I'm Using Windows Desktop Docker. The Python script I showed you does work after some trial and error to get to work. My OpenWebUI is running from WSL windows 10. ollama works fine and all options work in it also. I want to add this to it. Can you provide some thoughts? I know others have as you also..  Using  http://host.docker.internal:8000/v1, or I should say trying to. This was an after thought :) 
 Conda Installed Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32. 
Thanks in advance if you can help me get it going.. :)

**Comment by piovis2023** [comment]
@MovLab2 Great you got this going. Could please provide the script and/or steps? I'm struggling to get this going on Windows 11 OS too.

Thanks again

**Comment by MovLab2** [comment]
> @MovLab2 Great you got this going. Could please provide the script and/or steps? I'm struggling to get this going on Windows 11 OS too.
> 
> Thanks again

https://github.com/chrishart0/open-webui-nvidia-cuda-setup               try this

**Comment by piovis2023** [comment]
Thanks @MovLab2 The link is a linux solution. 

As I'm on a Windows 11 OS, what are you suggesting?
