### ISSUE TITLE
What is the input limit? is it configurable? examples of concatenating multiple .mp3s?

### ISSUE THREAD

**Issue by russellballestrini** [matatonic/openedai-speech#76]
What is the input limit? is it configurable? examples of concatenating multiple .mp3s?

```
# TTS Speech Example in Python
import openai

client = openai.OpenAI(
  api_key = "YOLO",
  base_url = "https://speech.ai.unturf.com/v1",
)

with client.audio.speech.with_streaming_response.create(
  model="tts-1",
  voice="alloy",
  input="I think so therefore, Today is a wonderful day to build something people love!"
) as response:
  response.stream_to_file("speech.mp3")
```

**Comment by matatonic** [comment]
If you use the default server settings there is no hard limit, the server will process sentences at a time for as large an input as you can pass. The official API is I think 4096, but it's much higher than that in this server.

**Comment by russellballestrini** [comment]
https://ai.unturf.com/#client-side

![Screenshot_20241111_074412_Firefox](https://github.com/user-attachments/assets/800503cc-6aec-4a18-a344-b2afb5ddf32e)
