### ISSUE TITLE
The Coqui backend can only synthesize English at the moment.

### ISSUE THREAD

**Issue by zhy844694805** [matatonic/openedai-speech#8]
How can the Coqui backend synthesize Japanese, Korean, and Chinese?

**Comment by matatonic** [comment]
That's true for now yes, the openai api doesn't support other languages at the moment - there is no way to pass a language. If you want to hack another language (Coqui supports 16 languages), you can change the hardcoded language here:

https://github.com/matatonic/openedai-speech/blob/main/speech.py#L40

```python
        file_path = self.xtts.tts_to_file(
            text,
            language='en',
            speaker_wav=speaker_wav,
            speed=speed,
            file_path=file_path,
        )
```

**Comment by matatonic** [comment]
If I added support for a `language` field in the voice_to_speaker.yaml file - would that be of use? That should be easy for me and not break the API.

**Comment by zhy844694805** [comment]
Your help has made a significant difference, and I am deeply thankful for your efforts. It is people like you who make a positive impact, and I am fortunate to have your support.

**Comment by matatonic** [comment]
@zhy844694805  I hope the latest update works for you, it enables language changes in the voices config file now.
